services:
  main:
    build: .
    volumes:
      - ./rb_ws:/rb_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.XAuthority:/root/.XAuthority
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      DISPLAY: ${DISPLAY}
    network_mode: "host"
    platform: "linux/amd64"