services:
  main:
    build: .
    volumes:
      - ./rb_ws:/rb_ws
    devices:
      - “/dev/ttyACM0:/dev/ttyACM0” # INS
      - “/dev/ttyACM1:/dev/ttyACM1” # INS RTK Correction
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
       - "0.0.0.0:8765:8765"      # foxglove bridge
       - "0.0.0.0:8760:8760"      # Asset server for loading stuff into foxglove
    platform: "linux/amd64"