services:
  main:
    build: .
    volumes:
      - ./rb_ws:/rb_ws
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "${WEBCAM_PORT:-/dev/null}:/dev/ttyUSB1"
      - "${RLSENSE_PORT:-/dev/null}:/dev/ttyUSB2"
      - "${TEENSY1_PORT:-/dev/null}:/dev/ttyACM1"
      - "${TEENSY2_PORT:-/dev/null}:/dev/ttyACM2"
      - "${TEENSY3_PORT:-/dev/null}:/dev/ttyACM3"
      - "${TEENSY4_PORT:-/dev/null}:/dev/ttyACM4"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      DISPLAY: ${DISPLAY}
    network_mode: "host"
    platform: "linux/amd64"
