name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Getting changed Python files and Analysing the code with pylint
      run: |
        git fetch origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
        echo CI_COMMIT_SHA=${GITHUB_SHA}
        tmp_files=$(git diff --name-only origin/main ${CI_COMMIT_SHA})
        echo "Changed files are $tmp_files"
        if [ -z "$(echo "$tmp_files" | grep "\.py")" ]; then exit 0; else echo "Python files are found"; fi
        tmp_pfiles=$(echo "$tmp_files" | grep "\.py")
        echo "Python files are $tmp_pfiles"
        if [[ -z "$tmp_pfiles" ]]; then
          echo "No files to lint"
        else
          echo "Running Linter!"
          pylint --rc-file=/home/runner/work/RoboBuggy2/RoboBuggy2/.github/workflows/.pylintrc $tmp_pfiles
        fi
